# Encrypt this file with: sops --encrypt --in-place secret.sops.yaml
# Generate strong passwords before encrypting
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-secret
    namespace: security
stringData:
    INDEXER_ADMIN_PASSWORD: ENC[AES256_GCM,data:sAqvD2hyXEeei4ube0e2UyAfL9s=,iv:TJM6j8qBUDde778cW+zYLG3TMUvzh9538UA4p7ODtsg=,tag:fh7DzEcqE9tMRVHqHwJZYw==,type:str]
    INDEXER_KIBANASERVER_PASSWORD: ENC[AES256_GCM,data:L7mYOpMNnNXbLBirJ+Uq+ph8Pms=,iv:ojSRuXaMzTPUTsuQoxuWl62bCAjD6crOKCYIB8SwcHM=,tag:EVdg8CvUi46NLygp7LERkA==,type:str]
    WAZUH_API_PASSWORD: ENC[AES256_GCM,data:ku3NlEDHGPy8TpPGgfb+b1gJjxA=,iv:0LRhznuyac457XDz6f2p2fnQiCUXOM2/taDuQ9rexug=,tag:jmq7/JHz1akH28hwYOttXQ==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ0NlaEJGWlNwMjVoOXc4
            clM3NzNjeG96RkxwbWd4cTNqd3dNR1p4dERvCjNwbk1DWDlUSU45MVFDRnQ5aDIx
            WkxjRmttVzkyTHRUdE9Xam1MdU1IYncKLS0tIE1TdFFHeWE1TitZbW5DWkxUWTd2
            d2xjU0gxMVRnWnZ2eTVhbmFCTnZKdlkK2BcXswMyXNbDxojWZf8duLLn3+9YubHk
            quE/XBsnlOJkcr3iUu8WmHWZhBjuI5Z98MNGpRFIWNCE0KZWfeNdbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T01:59:13Z"
    mac: ENC[AES256_GCM,data:7LUT3taIxhUCq8BgeRwcynYaCyAnn9Hdy+OuHVH6is/PinavnY4gJTnuQgpTEyVQoI4O4BQNniBWeQTklemLNrRKt5y809MEs32l5Ao6gBmoTwY1z8kWvAZF4JiSJW6fTr6i2d5rYa8jsWv0icMM1PoWBoXohLBYppxm7swvfn4=,iv:mUHXcW5qpxvq/i5IJL0V5dGuaR7t8QFSW9IvOKv6174=,tag:sHc3yuHPWqZelujEbdZrAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
