# Encrypt this file with: sops --encrypt --in-place secret.sops.yaml
# Generate strong passwords before encrypting
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-secret
  namespace: security
stringData:
  INDEXER_ADMIN_PASSWORD: ENC[AES256_GCM,data:pYinznZHYpaKC3+EtEI+FK/TbPU=,iv:Kp/QrQPJQHPiiewQZG7XWUoYOIHrL7fuZf61gybLEwk=,tag:ekAHhwhxW/V6v3Mi7mncIA==,type:str]
  INDEXER_KIBANASERVER_PASSWORD: ENC[AES256_GCM,data:LowP2Cnwx+KIisCutZ861K4K+ao=,iv:uV0XbLtGwApGpCXsEviz66y9sXZALe2kh87G7sIwBFg=,tag:7UzRv3ewp6fDwDhXWDbTiA==,type:str]
  WAZUH_API_PASSWORD: ENC[AES256_GCM,data:F7gVcbecfeol6tbCUFVpA1X2WPk=,iv:dssOkqfuYEV3ZJ0tjX6+Cu8qzVY4EqSfKu1/EPADDcc=,tag:sO0Rf0wbB62+pzFdEWgfbw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ0NlaEJGWlNwMjVoOXc4
        clM3NzNjeG96RkxwbWd4cTNqd3dNR1p4dERvCjNwbk1DWDlUSU45MVFDRnQ5aDIx
        WkxjRmttVzkyTHRUdE9Xam1MdU1IYncKLS0tIE1TdFFHeWE1TitZbW5DWkxUWTd2
        d2xjU0gxMVRnWnZ2eTVhbmFCTnZKdlkK2BcXswMyXNbDxojWZf8duLLn3+9YubHk
        quE/XBsnlOJkcr3iUu8WmHWZhBjuI5Z98MNGpRFIWNCE0KZWfeNdbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T01:42:30Z"
  mac: ENC[AES256_GCM,data:eGJbmrvkQPeuvpQd9n063C7hUYSBbGn8D2ed/Tt2xgFm98qWsdncvxrGbRTfl0Bcgct64maYjKF9MDyC/61JqEagzJ6b/UH9pvsopj8O6MvJvX5K9X+mFdsr4mUu+zFp4Bm7GLSP0P5OZ67BDeYRju1obsyemfzrIm2Q2e7ZqCE=,iv:MG30buTZkpynzJVnnNzgezrvFRwE6qAOYEhd3j4LGAs=,tag:h7rmvWUPcNop7QEzkO7fKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
