---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    # Storage class configuration for NFS
    storageClasses:
      - name: qnap-nfs-democratic
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - nfsvers=4.1
          - nolock
          - hard
          - retrans=3
          - timeo=600
          - rsize=1048576
          - wsize=1048576
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    # Snapshot classes - disabled (VolumeSnapshot CRDs not installed)
    volumeSnapshotClasses: []
    # Uncomment if you install snapshot CRDs
    # - name: qnap-nfs-democratic
    #   deletionPolicy: Delete
    #   parameters: {}

    # Driver configuration for QNAP NAS with NFS
    driver:
      config:
        driver: nfs-client
        instance_id:
        nfs:
          # NFS server connection - using existing /talos export
          shareHost: 192.168.100.180
          shareBasePath: "/talos"
          # NFS v4.1 specific options
          controllerBasePath: "/talos"
          dirPermissionsMode: "0777"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0

    # Controller configuration
    controller:
      enabled: true
      strategy: deployment
      externalAttacher:
        enabled: true
        image:
          registry: registry.k8s.io/sig-storage/csi-attacher
          tag: v4.8.1
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      externalProvisioner:
        enabled: true
        image:
          registry: registry.k8s.io/sig-storage/csi-provisioner
          tag: v5.3.0
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      externalResizer:
        enabled: true
        image:
          registry: registry.k8s.io/sig-storage/csi-resizer
          tag: v1.9.0
        extraArgs:
          - --handle-volume-inuse-error=false
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      externalSnapshotter:
        enabled: false  # Disabled - VolumeSnapshot CRDs not installed
        image:
          registry: registry.k8s.io/sig-storage/csi-snapshotter
          tag: v8.2.1
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      driver:
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: latest
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi

    # Node configuration
    node:
      enabled: true
      driver:
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: latest
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
      driverRegistrar:
        image:
          registry: registry.k8s.io/sig-storage/csi-node-driver-registrar
          tag: v2.13.0
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 100Mi
