---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"
    
    # Storage class configuration
    storageClasses:
      - name: qnap-iscsi-xfs-democratic
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: xfs
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    
    # Snapshot classes
    volumeSnapshotClasses:
      - name: qnap-iscsi-xfs-democratic
        deletionPolicy: Delete
        parameters: {}
    
    # Driver configuration for QNAP NAS
    driver:
      config:
        driver: freenas-iscsi
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.100.180
          port: 8080
          # Enable this for HTTPS
          # allowInsecure: true
          apiKey: YOUR_QNAP_API_KEY_HERE
          apiVersion: 2
        zfs:
          # Dataset path on QNAP
          datasetParentName: qts/kubernetes/volumes
          detachedSnapshotsDatasetParentName: qts/kubernetes/snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        iscsi:
          targetPortal: "192.168.100.180:3260"
          targetPortals: []
          interface:
          namePrefix: csi-
          nameSuffix: "-clustera"
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0
    
    # Controller configuration
    controller:
      enabled: true
      strategy: deployment
      externalAttacher:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-attacher:v4.8.1
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      externalProvisioner:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      externalResizer:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-resizer:v1.13.0
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      externalSnapshotter:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 200Mi
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.10.2
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
    
    # Node configuration
    node:
      enabled: true
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.10.2
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
      driverRegistrar:
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 100Mi
