---
apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-qnap-api
  namespace: kube-system
type: Opaque
stringData:
  # QNAP API key - you need to generate this from QNAP NAS
  # 1. Log into QNAP web interface
  # 2. Go to Control Panel > Applications > API Keys
  # 3. Generate a new API key with admin privileges
  # 4. Replace the placeholder below with your actual API key
  apiKey: ENC[AES256_GCM,data:PLACEHOLDER_ENCRYPTED_API_KEY,iv:PLACEHOLDER_IV,tag:PLACEHOLDER_TAG,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        PLACEHOLDER - Run sops to encrypt this file
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T00:00:00Z"
  mac: ENC[AES256_GCM,data:PLACEHOLDER_MAC,iv:PLACEHOLDER_IV,tag:PLACEHOLDER_TAG,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
