apiVersion: v1
kind: Secret
metadata:
  name: vector-indexer-auth
  namespace: observability
stringData:
  INDEXER_ADMIN_PASSWORD: ENC[AES256_GCM,data:b6be1M3L5XzQKgIgosGKwgKoG0U=,iv:SQHlcE6SxghEZaqvLuZt6P1LkG6JGR+BoOI6CbypJg0=,tag:k4jd9JfrQ6jFoH5BlIL2gg==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSXY3c0lIaE5mNnVIemcz
        NXBnZnhuYlVUWTAyTkxHSjZHVE43dmk2S0dZCnlYbWFBQWI5K2JUcHkwY2E1bGdp
        bFdSblgwN2I2ajZJRmdNWFpzU3BQQlkKLS0tIEZUOHNIdjh3dHBLVXlmRlcyUlhY
        T3lwVVNVamhWb01aUVNKYXpMOVNPWXcKav2F6obWlHjxkAjmLPpR552ruJqs1AP7
        svmlU0XiXtvowDpbqKrOEO0lpEuXVnoXvpXABDBuTzgMr+0RYCtnrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T01:42:41Z"
  mac: ENC[AES256_GCM,data:syxNUnn9kl/U5tz3jqu95VqiQcs+EBwuDOemYKrMT+unhl3pgfEYM3TdLuIDXgcZ1LEOmOrDwsc3nOBl3JJXtbdUzpCvrNH93UewNfMz6apjHddD3TnnBFTYwMwUbXS3i9xOw1u7sa5bObLBEiyXqqys51rdv7k8pk+hGg1buqA=,iv:eDaPZE3pcX+p+lGUvma2sc+plpiBo+ih3uZfpJw+TXM=,tag:XXqeauuYB4iiXNwqKJdeYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
