---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: observability
  annotations:
    lbipam.cilium.io/ips: "192.168.42.12"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: vector
  ports:
    - name: syslog-tcp
      port: 514
      targetPort: 6514
      protocol: TCP
    - name: syslog-udp
      port: 514
      targetPort: 6514
      protocol: UDP
