---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beets
  namespace: media
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/beets/app
  wait: false
  interval: 30m
  retryInterval: 1m
