# yaml-language-server: $schema=https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#secret-v1-core
# Encrypt this file with: sops --encrypt --in-place secret.sops.yaml
# QuObjects bucket: create a bucket named "juicefs" in QuObjects on the QNAP
# Access key/secret: QuObjects > Credentials tab
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: juicefs
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: ENC[AES256_GCM,data:fvkW/mCiLQdZ,iv:kRqHccyqtvLFuLlwjcSlM9jRX9mPYGU22qtjMMterH4=,tag:ByYC4P0MMeKMaNxc2mpMLw==,type:str]
  metaurl: ENC[AES256_GCM,data:3ziMwXxeDpd+2dlvCuhWWac5t6ctVZVtXaZ9lHlfImvi6Y/oFLZ2PImtRwGqgjkGLKeXNWBtX27d3ss/eSaDbtCtcLu7LwP1FK5b9GN9scEIBD9KoubgFX/7/8s7pF15QGl/qRvA5H+6dPZEhmIA7xsQiqNyA4+c9qPSIA==,iv:0lfvU2wANloi9bCbOZOi2ZwTm6tJksepwXj1DejBKDg=,tag:oJ23Jvk4XSMxdHLjzODtdQ==,type:str]
  storage: ENC[AES256_GCM,data:f6Q=,iv:GSzr1ucmZcwjlCE7PcKuagFnJ5kU3CkJDY4yO65rjS0=,tag:Cp/vkUxOk8CRJdk1ylgi/w==,type:str]
  bucket: ENC[AES256_GCM,data:L93yGW71C0gOhE/MZWOd9BLsix5WJwgAacurrxlyjLDdvtMH3AI8Zg0v,iv:VDDA+W0uinJF4mIoJOKoWYNZcReODlvgyOELEUr2u6Y=,tag:twYspYJnC3m/WSZ4MBeMQg==,type:str]
  access-key: ENC[AES256_GCM,data:vCQ/okfq+IDS6XOhjtRhQLCJhEgCINOsz35o,iv:taqWGIgMyoheusbxzA5pe3SpSvJxRmBistrwNISBEWc=,tag:WkYrSGxTaxWwORHozq7ZFw==,type:str]
  secret-key: ENC[AES256_GCM,data:FD9KBKbUYwRNcm7wZifdt6tIZd87VHwAR73FwB2QOng=,iv:UXx37ktLX1FjK7m2wm5W1QbUcX5IRQDtN/DMrYE5Jy0=,tag:+QK5LEIWQEE4J1EfoN4SsQ==,type:str]
  format-options: ENC[AES256_GCM,data:EwkTgvyP96udl/FciaCmJJquZhgGv+vmME75qg==,iv:a9D1Cu15biKZaAPjPLyQF0HUyM6DmLuFBloK+i9tcfs=,tag:TOjze3i6lXNmh9lkSxT0xg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eFI0eGUwK3BVMUpFcmFw
        NGxHT3MvSE1rZis1ZU1zZlFRUDYvZ2JHS1V3ClR2WkRVVUVzcW1rM1NSTXRiZUp3
        eTFIRXpNN3lpcUVVWVZOYU5lRURjclkKLS0tIHY5T2FFMTNzMHJzSERKL3QvRVpO
        TkxQTTNlMWdXcC9rdkxkLzUvY3QwazgK9mZjryP1AY9gl2kf0LCV8EJDpFGgs2BI
        41UvVuS+z0pJajWGeRNe02VdHAKCCFcGqCeEMn9Mu86QniN7JV0DXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-10T22:53:13Z"
  mac: ENC[AES256_GCM,data:AdvHBbrwR+VY5M6DcvmakHbvWGjC5EvU8acxL19V1PiXPqvZTBvoWMNXt8WU1tKUZdcoNQ+bQ4XOFEtMbA/p+G884oZzw2H1hxZrStZSvmnU6vYglt2e6HWo8rqzJfJEtmN3O2SMPAl2gffSt1UtrCmoBE5WQ9fPyXsLIaR2oZI=,iv:12471MsbLYHc+E6VqOXJyLGtlJ+xJKu/DEzDYQ/j1Zc=,tag:amH6LFO0WCLXMqfmITaAcg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
