---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media-smb
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: sabnzbd-media-smb