apiVersion: v1
kind: Secret
metadata:
  name: homepage-widget-keys
  namespace: home
stringData:
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:Gp76pYoMRObkcbBDVxoIwqZts2/S673N17bx2P//hoU=,iv:h+a3d0mJCL2Ft9/s9Dj5l7lykcRRfZhMKRjC1nMa7Xo=,tag:4UVOr/qtjROg5QKUQhtRmA==,type:str]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:Cm0y8qhc9JGubt4SQn5V/cpg2cqbdS2IUGwAFBIPZxk=,iv:8LLsgzzqxZ+DvedcBnyWodarQBB9zdV1myJdN29ggRI=,tag:b+2ug5sygkJ0h77qa8F6iw==,type:str]
  HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:/jfHDdQ6VnyHXjbZ8VxmonGgPO+G7MbT7/nA4za7Wrk=,iv:jzk/IbgntfLeiKG3XefqpIG7gygZapKT8fwwZqitj+I=,tag:ND5Symj2c6eqiB9OloockA==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:Am5Th1ORJBAFSlnBq1Qbyc7P9nHSVUWp0ljgnujfjK0=,iv:L6Kw7rqzd7yhFlwx8cSxpw3xCodG9s4EQSBCpiPDYYM=,tag:yjSqfN80IrjPRF976QjGLg==,type:str]
  HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:3OPRht+pY7MyRMoLUnI+a1zVqgO0hPv69zKzis55hBM=,iv:4t/U7LEAn9U1yBIqtjOT3qJAvkQCBAk1TJ+7UKS5Me8=,tag:N/rOJDBA0vKDyvnBSLPdEw==,type:str]
  HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:r/cPbi/VGiVcnoIR9nzm4Nw0MzP45ZuWXhZmuMHUjOU=,iv:qamB5LDlQay+BHr0Yf6t8JzJDJYLkJtO7laSyetBWXM=,tag:v8BiXwNthNUfBiY1ifr6Uw==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:+I8kiqgeev3LeqfivJeV+ng1vy6qy6O/ZkhXWAWKXRg=,iv:z5KrNm12t8gQYL8RJ7YgBN5bHNWzbm8agRLcJEKQK2g=,tag:E6FXNwqVlC6qntyQ3qaBKA==,type:str]
  HOMEPAGE_VAR_JELLYSEERR_API_KEY: ENC[AES256_GCM,data:rYJn4YWjyQ3na9NsbtWTcB5ZeWp51DulNwA6O1gwFEv/+CCJFATfLPt4o5KF25hL3Aqs6Q1R7yE+1X8UgJJzI5jZn4w=,iv:5g8J2ZjxA2JW1Qxj7FdVtQq+TtrefHwgek652mBaeEE=,tag:AGIe2wJZoUHd/DgdwtXP1A==,type:str]
  HOMEPAGE_VAR_IMMICH_API_KEY: ENC[AES256_GCM,data:o8FQeBRQIXLUj2+ovP/Zru99ZkOEGue6Y/edCWOAZpWuBPXybvYzcOs=,iv:cTbdYghiiPB+1uNwiPV6hB/CgvKuZJ905KHwKThfuw4=,tag:n/ge4g6QSN0ehNo4Y9FZlw==,type:str]
  HOMEPAGE_VAR_GRAFANA_TOKEN: ENC[AES256_GCM,data:gbATinY5Di9Vg63MfwoJ1rkURqqPbr88tqwRb65Ja5okcsB/DR1ChBhgLQFMGA==,iv:S9Fgk4fDKs2L3D1BQBVcn6QOuW7oKmA7lXmwoh4uCug=,tag:hqwc+thlFhLLU8hL7DDlRw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY2dMZ2o4SEx3Wkc5OVF4
        NDU1eGdaT05lRzFJMTdLSTg2eTdRV1hBbm5zCi9BQlRyV0xpU3RJUzNnWVpoZi9J
        SFVwZVNCZTRUOFpNTmVLdFJUL2plS3MKLS0tIGxPQ3VLMkVQVXduNk94NGVhTkJN
        bFBWbUsvUllPL1MzVWxxeWVJYU5hSTQK/46irAURvEMgFq2yxAjluEa+l+m2FOEh
        zrDpkfYZ2R5om5rG1HbWvDq3WbsoXPlyGF3XiayyYPDl6IiuF8SHDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T11:43:41Z"
  mac: ENC[AES256_GCM,data:LBbRs+cnQ1otGW0e0urfskJj5af5ddSSWMkYcrHOjYvKYOqGzuGKrripHpjb2yUbZf/7ho1dGvqJo0tn32a9HJF4NtIdmsBPRSO42P6McWAR6cQzTqbuab+8jXrPj+oNl1EiENIwSmnM+z8n/bFEHp41o77Iae4Re8JBSw764As=,iv:iB/bAGpvSiAuUjpzhn8h2uJR4wAra0XgRURXXpWbUjQ=,tag:ylqA0RpvwBsYTkjUxoZ5Xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
