---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-data-iscsi
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: jellyfin-config-data-iscsi
