---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: beets-data-local, namespace: media }
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 2Gi } }
  storageClassName: ""
  volumeName: beets-data-local
