# yaml-language-server: $schema=https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30
# IMPORTANT: encrypt before committing:
#   sops --encrypt --in-place kubernetes/apps/ai/litellm/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
  namespace: ai
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:44eF1CJ9m4YO+8AzoLwX5CPOZyarSAinb69YE1na5GYcYgH46xxOsCC1f1Spz4dejRZu,iv:wX1FF3lE1oa43/SKZBDtoR1uvtLAMImFspkQzRgGDVA=,tag:VuUTEJ51/nT3Vh3j9ETAaw==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:BFN7wvuEl+oequiFFoVBsgDEoAxq2Bv6JMTU8fs44TY=,iv:Oyhgii707dTEpV3U6MWNmuO8CJgk8Ru1CeEbLpATYIk=,tag:3fyr6U0Eoog1226rPqcDLA==,type:str]
  UI_USERNAME: ENC[AES256_GCM,data:JusTx9c=,iv:awenua9Y54IsXNqAzReaXsyA08gwj9N2nKx1xrlYUyY=,tag:IKhjUVHxHZ8YTY1pp75Mgw==,type:str]
  UI_PASSWORD: ENC[AES256_GCM,data:aadkmT5Xj0wcsWbtFD052dje3bQ=,iv:YXE4sBbPqPGrTdFRB7FsWtXFlTnLAN+R0h3TSf9Oj5g=,tag:uGReTp0akjlnpRIm6zDBMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxejBvc2ZVL0RPb0hzY2pF
        Y202Z0ZoU1RVUGx6SnNBU3VOY2s0K0QzZmhZCkVGcWlzL1ovNm13RE5GYkh5NHpT
        aCtxUWVueWliVzhzUDFWakVNU3JYMGcKLS0tIEJ0cGM5SmEvUGM3STd1Qnp4cWpp
        b2dtdnB1SXVKdlhZTTdjbkZ4YzJFWFkKCPYSQocUv4jHWT6ZelmXh4Oajfr2Bzyk
        /hQrYIqorgk0gf3rrM+1kVFXp2ObdvUOu9kLeu4nVOcGPZB/pkkgcQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T14:13:17Z"
  mac: ENC[AES256_GCM,data:mZ23V38eNKyyIX8zwoZ1FiscbDKlDqu4u8oYNCgdKSsFJpXE0ikVdQkjN/PbOh7X9ymklirYDKeMDFrQmQTxnRt6j73Db/82KY1DEXCohqrr8AclNw+vICBHiNQEYNnTKUfSoXCUwB0pYi+dQHQ5xQfWYxvm+CF8VuoLWs1i81k=,iv:OLdUwG/lY55j86cgWgtUK3EoqjLnRFd5xmQ4mgf4UfY=,tag:AqQD8IKSX0gPo8R1nNW8og==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
