---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm
  namespace: ai
  labels:
    app.kubernetes.io/name: litellm
    prometheus: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
