---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cilium
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    autoDirectNodeRoutes: true
    bpf:
      masquerade: true
      # Ref: https://github.com/siderolabs/talos/issues/10002
      # Note: hostLegacyRouting is for Talos compatibility, conflicts with hostRouting
      hostLegacyRouting: true
      # Tune conntrack settings for NAS-heavy workload
      # Faster cleanup of stale connections to QNAP NAS (SMB/iSCSI/NFS)
      ctTcpTimeout: 21600  # 6 hours (default: 21600)
      ctAnyTimeout: 60     # 1 minute (default: 60)
      ctTcpTimeoutFin: 10  # 10 seconds (default: 10)
      ctTcpTimeoutClose: 10  # 10 seconds (default: 10)
      # Increase eBPF map sizes for high connection counts
      mapMax:
        ct:
          tcp: 524288  # 512k TCP entries (default: 256k)
          any: 262144  # 256k non-TCP entries (default: 128k)
        nat: 262144    # 256k NAT entries (default: 128k)
    # Bandwidth manager without BBR (requires hostRouting which conflicts with Talos)
    bandwidthManager:
      enabled: true
    cni:
      # Required for pairing with Multus CNI
      exclusive: false
    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    # NOTE: devices might need to be set if you have more than one active NIC on your hosts
    # devices: eno+ eth+
    dashboards:
      enabled: true
    endpointRoutes:
      enabled: true
    envoy:
      rollOutPods: true
      prometheus:
        serviceMonitor:
          enabled: true
    gatewayAPI:
      enabled: true
    hubble:
      enabled: false
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: "10.42.0.0/16"
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    # Enable connection tracking for external services (NFS)
    enableExternalIPs: true
    # Optimize for long-lived connections (NFS mounts)
    installNoConntrackIptablesRules: false
    l2announcements:
      enabled: true
    loadBalancer:
      algorithm: maglev
      mode: "dsr"
    localRedirectPolicy: true
    operator:
      dashboards:
        enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      replicas: 1
      rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    socketLB:
      # Enable for all pods to accelerate TCP connections (including NFS)
      enabled: true
      hostNamespaceOnly: false
