apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: observability
type: Opaque
stringData:
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: grafana-postgres-rw.observability.svc.cluster.local:5432
  GF_DATABASE_NAME: grafana
  GF_DATABASE_USER: grafana
  GF_DATABASE_PASSWORD: changeme-grafana-db-password
  GF_DATABASE_SSL_MODE: disable
  GF_SECURITY_ADMIN_PASSWORD: changeme-admin-password
