---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-app
  namespace: observability
stringData:
  username: grafana
  # This will be populated by CloudNativePG automatically
  # The actual password will be in the grafana-postgres-app secret created by CNPG
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: observability
type: Opaque
stringData:
  admin-user: admin
  admin-password: ${GRAFANA_ADMIN_PASSWORD}
