---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-data-local
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: soulsync-data-local
