---
# yaml-language-server: $schema=https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: security
spec:
  instances: 1

  # Use PostgreSQL 18 to match the existing data
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB

  storage:
    size: 10Gi
    storageClass: qnap-nfs

  monitoring:
    enablePodMonitor: true