---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.22.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: security
      interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    monitoring:
      podMonitorEnabled: true
---
# yaml-language-server: $schema=https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: security
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB

  storage:
    size: 10Gi
    storageClass: qnap-iscsi-xfs

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-app

  monitoring:
    enablePodMonitor: true
