---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-iscsi-xfs
  resources:
    requests:
      storage: 10Gi
