---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./add-topology-spread.yaml
  - ./add-default-resources.yaml
  - ./disallow-latest-tags.yaml
