---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: observability
data:
  config.yaml: |
    storage:
      type: postgres
      path: "postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@gatus-postgres-rw.observability.svc.cluster.local:5432/$${POSTGRES_DB}"

    web:
      port: 8080

    ui:
      title: "Status | clouddrop"
      header: "Status"

    alerting:
      discord:
        webhook-url: ""  # set via env override if desired

    connectivity:
      checker:
        target: 1.1.1.1:53
        interval: 60s


