---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: profilarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bjw-s-app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values:
    controllers:
      profilarr:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: santiagosayshey/profilarr
              tag: v1.1.2
            env:
              TZ: America/Chicago
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 6868
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 6868
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1024Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups: [65539]
    service:
      app:
        controller: profilarr
        ports:
          http:
            port: 6868
            targetPort: 6868
            protocol: TCP
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: profilarr-nfs
        globalMounts:
          - path: /config
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: profilarr-media-smb
        globalMounts:
          - path: /media
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 6868
