---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_clusters.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr-postgres
  namespace: media
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: radarr
      owner: radarr
      postInitSQL:
        - CREATE DATABASE radarr_logs;
        - ALTER DATABASE radarr_logs OWNER TO radarr;
  postgresql:
    parameters:
      max_connections: "50"
      shared_buffers: 128MB
  storage:
    size: 5Gi
    storageClass: qnap-nfs
  monitoring:
    enablePodMonitor: true
