---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Official Kubernetes CSI NFS Driver
    # Simple and reliable NFS mounting for any NFS server

    controller:
      # Controller manages volume lifecycle
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          memory: 200Mi

    node:
      # Node daemonset handles actual NFS mounts
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          memory: 100Mi

    feature:
      # Enable volume expansion support
      enableFSGroupPolicy: true
      enableInlineVolume: false

    # Customize driver name if needed (default is nfs.csi.k8s.io)
    # driver:
    #   name: nfs.csi.k8s.io
