---
apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-qts # Required. Name your backend in Kubernetes.
  namespace: trident
spec:
  version: 1
  storageDriverName: qnap-nas # Required. Support 'qnap-nas'(latest) or 'qnap-iscsi'
  backendName: qts # Required. Name your backend in QNAP CSI.
  storageAddress: 192.168.100.180 # Required. Your NAS IP address.
  credentials:
    name: backend-qts-secret # Required. Enter the secret name set in metadata.name.
  debugTraceFlags:
    method: true
  storage: # Required. Define one or more virtual pools.
    - serviceLevel: fast # Required. Name your virtual pool.
      labels:
        performance: performance
      features:
        tiering: Enable
        ssdCache: "true"
