apiVersion: v1
kind: Secret
metadata:
    name: backend-qts-secret
    namespace: trident
stringData:
    #ENC[AES256_GCM,data:9nQlISNgm5hSU9F+w5q93fG17C0kaVc=,iv:78856TIDjyEbeA0rkHTsXqP7T1n8mG4ljfn9udTckco=,tag:re6gXZbMMqnp1w9zzRa3Ag==,type:comment]
    username: ENC[AES256_GCM,data:fEry+8U=,iv:AtHqPMNeKuKQKKvFWF3dBHbFVMJGfeP67fpHu6Skius=,tag:Q8DhwjdTwpYcjYIFZhT6zw==,type:str]
    #ENC[AES256_GCM,data:2AITcJlAyOlIHNExM1dlMPmSBJu6EOo=,iv:Cb1V2+EvrdIFLcg8Unlo6XCjKANBjRY3M7YJqqa77I0=,tag:xdhrfvGzfgVPgtvWqcQAIQ==,type:comment]
    password: ENC[AES256_GCM,data:hXpUW96V6d3qFvsBiuu09EVkYPp446dZJaB6gA==,iv:tJVCmcr0tepR4zwBuJ9GY7RWu4dgfl4VEpwUsb4Fgk0=,tag:ZkaOMoRJ9CXs4MaxbuXvmg==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnT01aMHFoR1ZRSmdHTTZN
            MUFZNDhza3g4OUF5K0J6cUJzZFBkTUhYMm1rCjRiNWRkdnRLWHgvTTk5dmp6ZWJq
            OFlhVnpjWEMydUNybXhTRVdVMTlMbEkKLS0tIERnOEVWQy93UDc1OS9FekVyWFRI
            cE00NC9qQ3Q2N0x2SjJyVDVrak9nRUkK03Lpi02A8/fO7lyct1bJS+iiesGcUdT4
            AqVQQp4t9SiNZYNRNn/HBr4q/R8T82XNn0J7FOwYeBFAOXatlIGaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T01:27:21Z"
    mac: ENC[AES256_GCM,data:kal9ekXRDFjRB5Vk+OH3HyQmNI9PEdxcv0im0fwYnJXFs7P3UHVJRHgwf5SBmGpZN02TW/6UfL1l4GTg1V3iQw8xJYeBnrc3eSrj6ZZ9+m0kz8z5ygwiVrEsZB9BFm+CiYasXeZsejKyoDfUS2YIqISINEinLFG37tutDfRIeY8=,iv:9+8ltSlowMHkbVRPUIIjRwj+IuZdSglU4DWHcWcy8rU=,tag:oLp7ot6mfA+RRiy+Pz854g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
