---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-nfs-db-sync
  resources:
    requests:
      storage: 2Gi
