apiVersion: v1
kind: Secret
metadata:
  name: actual-budget-secrets
  namespace: home
stringData:
  ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:SpSM5XtHPLqafg3fOnqjaeucrXg1XsFUkqR+8ypMtRp3VQYdIEmijg==,iv:H0UMeq75zmTJCycO9kYJz/g7zsB0hKe7tNMaUzRYKg8=,tag:5qNcJU0/qQJucNugF+xILA==,type:str]
  ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:s83hkSuVLiI45rjOD8ol806cZ6pKkdLDW9dsWzlrQZ+3N1f+8xIH5FTn5p65Fd6ZOLt0wN0Bw3dqmOCNXxvj5mjyf/jzaTJQfQDb772OYdjkvW/eM5Szmopv/P3tDC4HqgMiIZmIClFYFA/cSULdycCNgEWrd7hBvtweBo3L4Ws=,iv:5RRumvD9VOEunXSnTrmjJBI7AAmJ8UGLqvVSNtPXVUM=,tag:bsTv3hrhEmd8CCq1Go3rvw==,type:str]
  ACTUAL_OPENID_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:jRMcTCAf77IMmzkQdbCwwzYi2oVEshV3xEjvn2lemQZaXb/zxdsiW8qifmYXIc3H/QkFXaoiO1KX,iv:o+f5P/kVWZP0AbTdUmGbmGXlYfGKzOnsQsbkUyxuAJs=,tag:+wwIUjwQ0RLlytFbF+139w==,type:str]
  ACTUAL_OPENID_TOKEN_ENDPOINT: ENC[AES256_GCM,data:ahZOXb+nVpEgk8LVxAxXi3lro3SmoFCliC6i7VjDUw65T40EkRMLWU2tDIdnPGuGU3mSiJ4=,iv:ZEHYSoQIBCZpvLnOHE5Cjz8vn1Lm3SE9T3fvei8A5B4=,tag:VUfNYONk/SNlDH4i/WuSVg==,type:str]
  ACTUAL_OPENID_USERINFO_ENDPOINT: ENC[AES256_GCM,data:AXaj0pDuD/HfZTFuUhRVuP61VpuhcnuyZvlvrmhaykvfo+0mJYki5Gi53qc6lPf2sRxKzvpXaaA=,iv:TEaytIdNOaVL8zdO2/Y1YXCIkScR7cLfLwXmI8XYQd0=,tag:pHWsEFzhr7EWYuasREjLJw==,type:str]
  ACTUAL_OPENID_SERVER_HOSTNAME: ENC[AES256_GCM,data:uauSBOhPDbjNfmz9ZRpp838thsS49X2S7nc70pvIu4+TIQ==,iv:RU33Yhr01yvgh6UwxTdJorbYowaXuQi1ORvSllhHUUU=,tag:uC7422CPPXRmqR/2QyyfRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RFg1TE42T3RZeEl0Vmll
        NjYyNzNRS3RkQmhUUUh2SEdNRkNjTHFMa0RFCjVzdy9RQm11cG1BWGtoYUNlTnk4
        UGlUMkhKT3kzSFF4YkVGQXlQVDhERzQKLS0tIGdtUWFMNk8xRno2M25ETkhnaHRj
        N2gyL0k4NEhDblJWRDhMWkZiQ0QwSkEKsY87jFB/HxhXRyGgVwyCp31a4Guwf3Ig
        2PZhSSdus87rJ2CNg5kwT9hSBFvwJuXByia3mJUcwrAyzbC2FONFlA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T19:56:45Z"
  mac: ENC[AES256_GCM,data:fAoWL2wJNTy0Lhy0p2h9SbSFFqxmGRF4yK20TtvO3Rx7tUpDVbe22kX5H1RpLXOtn+Ik5oQU2Yh5SZ7Hky5MIWC+8Hj2ZfbEnqGz/xi/Rhiy6HiOemzk1G9Mf642qDHVCrqK+toLR4WiD8lzDj2MSU8AzaoEK2iFPivBu5xL39U=,iv:xY304Nw9jzjWNK9IXPlZKZF3OtfLr/QZPX9Bhg/Plq8=,tag:VyTD++86k5GccJAphy1A8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
