---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-driver-smb
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Use the latest stable image
    image:
      smb:
        repository: registry.k8s.io/sig-storage/smbplugin
        tag: v1.19.0
        pullPolicy: IfNotPresent

    # Controller configuration
    controller:
      name: csi-smb-controller
      replicas: 1
      runOnControlPlane: true
      logLevel: 5
      resources:
        smb:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 20Mi
        csiProvisioner:
          limits:
            memory: 400Mi
          requests:
            cpu: 10m
            memory: 20Mi
        livenessProbe:
          limits:
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 20Mi

    # Linux node configuration
    linux:
      enabled: true
      dsName: csi-smb-node
      kubelet: /var/lib/kubelet
      resources:
        smb:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 20Mi
        livenessProbe:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        nodeDriverRegistrar:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi

    # Disable Windows support (adjust if needed)
    windows:
      enabled: false

    # Security context
    securityContext:
      seccompProfile:
        type: RuntimeDefault

    # Priority class for system-critical pods
    priorityClassName: system-cluster-critical
