---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-juicefs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: juicefs
