server:
  host: 0.0.0.0
  port: 8080

theme:
  background-color: 225 14 15
  primary-color: 50 98 73
  contrast-multiplier: 1.1

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
          - type: weather
            location: Chicago, US # TODO: set your city/country
            units: imperial
            hour-format: 12h
      - size: full
        widgets:
          - type: hacker-news
          - type: releases
            repositories:
              - siderolabs/talos
              - fluxcd/flux2
              - cilium/cilium
              - gethomepage/homepage
              - glanceapp/glance
      - size: small
        widgets:
          - type: rss
            limit: 15
            collapse-after: 5
            cache: 12h
            feeds:
              - url: https://www.talos.dev/blog/index.xml
                title: Talos Blog
              - url: https://fluxcd.io/blog/index.xml
                title: Flux Blog
              - url: https://kubernetes.io/feed.xml
                title: Kubernetes Blog
