# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.42.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.42.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "skully"
    ipAddress: "192.168.42.253"
    installDisk: "/dev/disk/by-id/nvme-Samsung_SSD_960_EVO_250GB_S3ESNX0J931509B"
    machineSpec:
      secureboot: false
    # Extensions: i915, intel-ice-firmware, intel-ucode, iscsi-tools, mei, nfsrahead, fuse3, util-linux-tools
    talosImageURL: factory.talos.dev/installer/ba9e90ad2f7305412fe2fca931f368d622f6a6c51b43988fdae88667de7f87a4
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:1f:c6:9c:aa:11"
        dhcp: false
        addresses:
          - "192.168.42.253/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.42.1"
        mtu: 1500
        vip:
          ip: "192.168.42.10"
  - hostname: "buzzy"
    ipAddress: "192.168.42.252"
    installDisk: "/dev/mmcblk0"
    machineSpec:
      secureboot: false
    # Extensions: i915, intel-ice-firmware, intel-ucode, iscsi-tools, mei, nfsrahead, fuse3, util-linux-tools
    talosImageURL: factory.talos.dev/installer/ba9e90ad2f7305412fe2fca931f368d622f6a6c51b43988fdae88667de7f87a4
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "78:55:36:00:a1:98"
        dhcp: false
        addresses:
          - "192.168.42.252/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.42.1"
        mtu: 1500
        vip:
          ip: "192.168.42.10"
  - hostname: "bolty"
    ipAddress: "192.168.42.250"
    installDisk: "/dev/disk/by-id/nvme-KXG70ZNV512G_NVMe_KIOXIA_512GB_928FC0TLFTB5"
    machineSpec:
      secureboot: false
    # Extensions: i915, intel-ucode, iscsi-tools, mei, nfsrahead, fuse3, util-linux-tools, nonfree-kmod-nvidia-production, nvidia-container-toolkit-production
    talosImageURL: factory.talos.dev/installer/afc99e225a931f3e06e8a3f624f792f6131deafc2f5aa243b23b622a47178cad
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "cc:96:e5:dc:44:5e"
        dhcp: false
        addresses:
          - "192.168.42.250/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.42.1"
        mtu: 1500
        vip:
          ip: "192.168.42.10"
    patches:
    - |-
      machine:
        sysctls:
          net.core.bpf_jit_harden: "1"
        kernel:
          modules:
            - name: nvidia
            - name: nvidia_uvm
            - name: nvidia_drm
            - name: nvidia_modeset

# Global patches
patches:
  - "@./patches/global/machine-features.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
