apiVersion: v1
kind: Secret
metadata:
  name: rangarr-secret
  namespace: media
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:pC5Jfsa2idFQsYPV7fchJzr15tg0b+J9vYOfdX41b0Q=,iv:oByeO0bdlQHz9UGXZHhdtPsoL7IBSTB60tusa/dofvU=,tag:4QTTh4DGHIaxF302dAImfw==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:I0LDBM/0QwEL2WdNMyx5qd1FAmzu3TsfyT4Fb7ADJPU=,iv:um32q4M017Yci/LsGBNAco/XSBApPAdHyBp9Y10FOXU=,tag:p8cCOQKCkSM2MlOaV87zKQ==,type:str]
  LIDARR_API_KEY: ENC[AES256_GCM,data:k8+HJflW7DQgyx24FTdsQh7gio8RvX5XTXPs7lFsMBw=,iv:XmTKzK8nZAcc1ktOkSiw+lZLdX0ZVtb9D6yXtVMpxMQ=,tag:dEZr9y8y0/18t28kijoqlw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VWxGaEU2dlhISkZEaEJK
        ZXBRcTg5NmlHYnRzeDlodEp2RVh0Y3BKMUR3CnNjaDlBd3BsRkxXTXArQVZUVll0
        MWFkWFRWU0t6R2VnSlZsU29TVFpmc2sKLS0tIDlDbmNhQVlSYy9NaFhYV2VkeUxE
        dkhVOXQ5bHFnd2JKR21BT1IzZHdLWUEKAiNqGvwez29F61anog6nXxicIFeqSRIk
        Qx7x9RGjks//pi17QoeMMJmJKU8tsDGy4M5kep0gBtKD77UEvogPIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T01:31:53Z"
  mac: ENC[AES256_GCM,data:pCN1aNK/jnmWAl3kyEqEU3lb6OhU2pG/N4Fo7y0Rd0INthIxH1ta3Ganw8v3kNEM6snP3aVBPAQ7VxOpw7TyDXPQU5YMj6KWbA1b2/Pa9Qtjwg5FcIwXIJucAvpARw35lBMwtvx42l3DCNnKy41uBi/dV1aHv2XyAYpjPHWnY00=,iv:SCz3polujIjxk4Gxmtt9o9htLUFjb9YZEc9hVTNXPFs=,tag:goW3mDdYV3yGGU9vWnrb2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
