apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secrets
  namespace: ai
type: Opaque
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Fn1ZXA+YP35DbWR9hMXfoK2BmDzNcwCXn2UvqwmKmMHG6Lzpkp3LlOVK7j+B8P/NNe3/MI8ucgNURsoelA++7Q==,iv:aMX9MCkYotnbvKbMx4eQLgBGJ/6EQ4+qtXZGJ0KE448=,tag:ELdEu515AMZq4shziMfQxw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc2ZCSTBTN0RhS2F0UXd3
        UEdJZ0lvVnhXQXRvQXUxTUFhRDg2eVg3SFNvClVkbzJtelFQaW9OZStsVFJvWVM3
        T2czVExTcGVzWWtDb1UyYTJYRTMvK1kKLS0tIE5ZM3o1c0dKb0JJelpnVzROMVFu
        bXJFcmdnRG0yYkZWcTBOMUwzcEVZZ1EKgERQps9Qw12orC58MbMoS51cfxmu1E49
        XT+F/0fq1A0oYv5avfPfevx7sbcnIa9eg9hSV/h4duOIKynETqPsew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T01:19:39Z"
  mac: ENC[AES256_GCM,data:G3EXrKE8VybDJOL15oy70GY4OLfcmiJfUFP/UG8UYUrTUJXJHuckRDDMFfLrxM2s3mIka48v4oASpxBvCdygWJxg92i7ssRGOHofGC7+KFZb0PZfDDBkcaLVwIdv+yd4cb0PYZ/SLKL4qJKLhzF+AVdxcSAF69hGI4eaY2dbL2Y=,iv:ccECLwQMADPrVqfceAdL9xLEGL81b6gIkuZi4lEPY0U=,tag:2yqsWZSDWNPAALAXVwfWpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
