apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: ai
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Fn1ZXA+YP35DbWR9hMXfoK2BmDzNcwCXn2UvqwmKmMHG6Lzpkp3LlOVK7j+B8P/NNe3/MI8ucgNURsoelA++7Q==,iv:aMX9MCkYotnbvKbMx4eQLgBGJ/6EQ4+qtXZGJ0KE448=,tag:ELdEu515AMZq4shziMfQxw==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:W+a6Y2lsWGPQW3yV/DDedb1rtIwEmiOtBVEge7A2JmYj7DvfLuC0NvzdYufNHnHdesP5,iv:FSrrR3C3MZaaxFHM+ucJCLFPdC6ZGv12HbGvHUHeXeM=,tag:yVqa/TCtggwj3lFIIM3jtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc2ZCSTBTN0RhS2F0UXd3
            UEdJZ0lvVnhXQXRvQXUxTUFhRDg2eVg3SFNvClVkbzJtelFQaW9OZStsVFJvWVM3
            T2czVExTcGVzWWtDb1UyYTJYRTMvK1kKLS0tIE5ZM3o1c0dKb0JJelpnVzROMVFu
            bXJFcmdnRG0yYkZWcTBOMUwzcEVZZ1EKgERQps9Qw12orC58MbMoS51cfxmu1E49
            XT+F/0fq1A0oYv5avfPfevx7sbcnIa9eg9hSV/h4duOIKynETqPsew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T14:18:12Z"
    mac: ENC[AES256_GCM,data:bJGig8tB5NT8fz4iCe904TMJlsy/n0AZeoT1Vi0xpFoNRZJCHmv6Vp4c/FR4BaDtrRRqPH7h8Ogc4mIWZooSuM5+eyma/yRvov/YcqvjO9VVQCErtY9XuX8XTNnTJ/kTA/B58sfuiXXCbWbJlnvZLg4eeVJ8x5diSZeDH5Z1AEQ=,iv:udYEkLpuTVev36qXYMZETMr4NXhVTNTA1Np5endFG6s=,tag:qkVZGRpLeRUxa0WQcfd/Sg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
