apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nzvz23B/lg7CJDQDJ464xU1EwQ==,iv:WdlBeZlraGT0bJmOtukS6Ol2CgX+tTZHon8d7QB4WUs=,tag:bp8n/MYd7uadzPBVDCDAyw==,type:str]
    GLANCE_LOCATION: ENC[AES256_GCM,data:fiF5WwFQB2cDcFghBJR3sgXlF+iG9Q==,iv:N+fZ+3aX1GJZfe+x5IwL4opCu69q/wBewURDVaIeJjY=,tag:6VZG9v/QXJyMOl1vJaSS/A==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMnZoeXEyK29RVmRXM21j
            UjdhU0pjMEdpbjBUR0R3WktOcUUxR25valdNClNqcTFocG9idHlvR05BRUdnR1E5
            TkU4MFFMN2VLdktqVHpvK2dSckpHV3cKLS0tIDlIOEE2RjBUUFZJZmVsTHB2cDZ6
            ZkxDaTdYZncvY2htM3A5L3p5OG5yOVEKmspW6nTFu/5hhGw15xm9fPB85P7ynMLd
            I/zhiKkJnTPIKFfTJsBbfn5vHQyHLMDduwlft9OPi32i+SH2VcVNUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T00:33:09Z"
    mac: ENC[AES256_GCM,data:+g6utaTIb58r3aZvL7n3wmMhYJ1ICDnfibMzULDm5jojIdqLau4KCiKDfOfQ+c7Cv/Hvax8Kkvudl3RPKv2+QeGdxpAwhVB6x5MgQIX6MsU8SB4Qt/gycFyJXZ1Nt3e3EBvLHV4qROEVuFA2I+d6VcKbGHxi/ibzaGkW6pTTb4w=,iv:grnhCIk881l7Bc7KVmModd6OXIlO8DlvgGRx47+U/Gk=,tag:YUM2+9G+CDV+BgljdKVaCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
