---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posterpilot-config-iscsi
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: posterpilot-config-iscsi
