apiVersion: v1
kind: Secret
metadata:
  name: posterpilot-secret
  namespace: media
type: Opaque
stringData:
  JELLYFIN_URL: ENC[AES256_GCM,data:YSYWd8fDhpN/voOk4mjCL7Kb7Da8pmpcV7v2e5fHuPgqEunU,iv:A8ZEIngj+8K4NqhNnowGUzUH9TUOOu9ZljL7VJm/dPA=,tag:luYkCSjCUXC0XaPnATYpOA==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:AvPP7bs7pi/4wzIhXlkkKEmppakZuwoqUF3mw2/u3Tw=,iv:I1iybdkgj24i//okb1IYAB5/J1nUa3tVTdovSk3eCNM=,tag:Ay1ORabeWvp2Bwud29USaA==,type:str]
  TMDB_KEY: ENC[AES256_GCM,data:BKMWD5uqJHkEYYn0juJl6Zq0H0YAVqKr8G9A/J9ywM3MCOGVguqholjgcTYU9PsnwVBi3vrpeny68/lYQnnV9ozo7hkoR0peSLMWBQr/eb3Bob++/nfMdKiKwAb7C2kH+ErVx8tyX0ECjHafbDCybSJLafg3X4miAO9eqVP1TxLtRRN3h1tBFQyPzI+KlWUPuQ665TCRdHr8SQU7Dbp6C0dR6RBKosonuAG8CObkfzNutakfjI3pnsCN+bMgp3eKtuT9Z/zEbaA9T9yUK+q0ada+bB2LM4OqPUbcg7tMrtGPPSG3c14hG9Jg1Fbhaas=,iv:bKFqQTZhFwwN/HBn0Anq95+iEFG18zS1Y6CqAzuUjaY=,tag:pNuoinKO/X6R24zZIBLzOg==,type:str]
  FANART_KEY: ENC[AES256_GCM,data:t9k7Aje9hWt1mUKH481DEuzH5EDfvcPSAhEmZcSxLoE=,iv:pXfLkWNPwsHQiqFpkFvrwz6p7W2X8sdZgSSr3xK/bFk=,tag:xL9y10a3JInzUQjA+igTBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NGJQWXN2ZERxZ2kzUE16
        TVMrKzZwV1l2L0Y2alg0T0N6VDBtWXZIdW53CldkWlU3UDJZaXJrWTR3Y3lDR2c0
        YWtxZzdwRDlZS3BZRGhteXdXYTQzaDAKLS0tIGUyUDZVU1VhdG9ISG9XcG1UbVgv
        bVJVaTNLNEh4Nkg4TzVuVlZBbHl4MGMKvWHFZD/FPZm3zg/ovGXQ9TAjmuqbK2Nj
        qKFLT17f4FfeTkh4ty+poVLJcwfXM0a80fPh8tIbFndHzk5aSR31KQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T00:10:45Z"
  mac: ENC[AES256_GCM,data:BwZ6KwQk/SND7IOTzDdQbEEXIdSlN4CJVdHNmtiGB6VN/LVFlNaYLqQEiPlMSyukSu8lEtjVA0lJCaYcvp7xf64PYE8Ff3/X46N/HmpjzTFLWDOluxU4bPvMbwGrcugnBJ9Sx30ZPEgmvB15ZXWm5E/nys0Y/YKbwfY/Ekw8uKs=,iv:XDC7p5Bs+ZyCCvorEQuOgFq6/qeoyyV9U2qW+fo7itM=,tag:SCcLJ9KS71RBUPg2bjr8pQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
