apiVersion: v1
kind: Secret
metadata:
  name: posterpilot-secret
  namespace: media
type: Opaque
stringData:
  JELLYFIN_URL: ENC[AES256_GCM,data:62rik/cfOqXMvw06kuTJ/Z69H55g5Gs6qsqJ0JZIrWfSdjZD,iv:R6j+6VDF9++V73INNIPktfcDdDZqDs6S094LGfN/6Oo=,tag:xv9R3FrGJH4wEeJ8GS9qXQ==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:Mo0UlJZH+d1Jej8DSfxywZHX5mKCbwPc9Pau3OR49PQ=,iv:pbkahng1WjQMMDyXsbDLz1jFd9CpxQ6gdtO4xrZlkiY=,tag:2qz4iuE0daG3VyobLG4qww==,type:str]
  TMDB_KEY: ENC[AES256_GCM,data:pDgGOiNeP0B4WbtvN3m6S03vHmD6SuFILUAT2JdnG5GfZRC3YiLy/V05D151361cNZxG1mv0v8TjiPzXUIawRZugjFKhMY963X8kKtrBw4QBVbQUpVhsBPa4K+Jb4M73lon3j0ZHpNNMrBMUQ3MjG5g8901pyxkYzi0Y6ySaX0vy7BV/1hsr7FysnqoXQXVmxe7jPt3FCs2YNGKKZR7aYVbBep/+EY4YnQgsubZb6HqSIOtsoKdG+VxCQCaaAdV9obqh+ZUOkUTpN2kyOT4Urz0BG3ypA8nUKNWaVR+gBhLU+IUEcvSWG5Uc909Vhu0=,iv:JEX5jg2rRmaAnLasJvzPBZJxgbUFajXHM/+lLISpt10=,tag:LwGhR0Hp4D5Qh1lUO3Mceg==,type:str]
  FANART_KEY: ENC[AES256_GCM,data:NTg3z/IMpHpjveq7NBJcK31/E61owHATzlFXU5CH05c=,iv:OmzWmL3haH32bhVvNO9s+CNAw/q4A6r5YLaDeSVzets=,tag:XGBEdN28ASqR6NkEsNhDIA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUDJ0SmtnVzRwSmNoNmN4
        MiswN3RYNTFPMzlwMVpoRmZvaUE3WGV2RmpnClljK3h5OXhjbnJHQUVENmRZekZ3
        NVAxeDUza0RCazV0N2w0UzE3WmM1eE0KLS0tIGk1Nm5kUDlqVi81Z0tjSW5Na2gr
        aDZROHo1NzBORUFERzVPVmpscCtVSG8KAiZJYV1PYCnRJ5XqsOucS4fh5iqAckhB
        MDk1wOJbZSfBr0dztYkFS1ul646qb88YxH/rtX7b5PVvzoZm2W6FGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T22:58:09Z"
  mac: ENC[AES256_GCM,data:NX6NfGgwr8M0KfLbmAZn/Tj9+nzbFQ8pBQLZBdzz2OEDEzieJlZPc0SfWJA6HLOFjAJBTr4dKihnJD8o4YxNIivqXiLs6VS0MqwWSPZkiBgE0VYgGi9JRcmI+cTOhb94NLG9TNZpI8gf7Y94wNMHQbzkBMHC8BHr5rD/mE7xgMM=,iv:1WHmtM8evJLNCi8lasWgdWF6kay4+MhoMgUHE0RzswY=,tag:jpHKdZo04jgjSTMRQFmPtA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
