---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: home
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: emqx
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: emqx-secrets
      valuesKey: adminPassword
      targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
  values:
    replicaCount: 3
    emqxConfig:
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop: ["ALL"]
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 512Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
