apiVersion: v1
kind: Secret
metadata:
  name: emqx-secrets
  namespace: home
type: Opaque
stringData:
  adminPassword: ENC[AES256_GCM,data:OuTlCYFLpIM=,iv:vbaoPWhv+9+xK/qDgeUyq46sVv1vB8gxdSrs+XlQCzc=,tag:swLiI2fRAFV4cTuTZnlpZg==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWUdGZUkzMFQ3bHJHQVRO
        b2RmQXhOa3Vaci90blhITkxpOWFPT3JjZmpZCisyVWVHekRybW9rQnpQcStqTy9B
        YU9FODB1MVNqck5nZDlYRXUyamhnb2cKLS0tIHJIdVNsRnZZWk9LeS9ia0NrTXlw
        b2o1cFFueHVwa2RrUjB3S3lUTTlOWU0Kc18sNa/r4MhH/dzf2oAvLIclnD9Tlz7x
        qdNOUwYmwrYhK3v2tXBNIwjs8Fe1dVdvS1DbZz0ZrkMaxRVyE5kGOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T21:05:41Z"
  mac: ENC[AES256_GCM,data:B2ydPp17/smmxxIYoPVeMnl3Hqin8pVRsldPtYX0G5AP6roTCjhvRe2I1Ci8MKZ4vae9FEgtS5A2k3iTEQ7ME4e7CTNTJ/e7L2W1YHHVeb8JYVO4HFi44a2hUENU2ifuG1ppRphPZaPrnz6547WEHx5IMR9eh2iu78bBwZB3Jxs=,iv:1QT7Za5a0snagFFuNjRYC0QKsmBME8Puy5O0VkldqEs=,tag:WyC0BbU8rJhHr8uW9Z4BTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
