apiVersion: v1
kind: Secret
metadata:
  name: emqx-secrets
  namespace: home
type: Opaque
stringData:
  adminPassword: ENC[AES256_GCM,data:iQ5bRss08RwNQYDJ3b1oIdb5SduX199pVStpO9JxOBo=,iv:bCeYem9OhB3TH87NQgzsLR2re6UqrevGSVghRtAu8NA=,tag:0AQHcIg1AWjrPvanYtkIgw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcEhSUjl2cEpKTEZmMUdH
        SDhiRXErMnVxSlpoM0V6V3RjMlhXb2N5K1RvCmNWbUJMeXNEcXhzYnRYZFVvRXBL
        a1ZCbWEzbXNpdkltOWh2dUNnbXdEMWsKLS0tIGdzMk1JelRjYmNuQXF2NFFubmNI
        NEIvQ1RYdWF4Z2lTVHE5WkZFWHRMREUKVuumySXb8Am8I+At40OMZRrXvjUQLADL
        GaHbkvdWWcClESqQWIjgR/ZYFCdXfWepHnMsaK2i7+BMLhd+Bt6OHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T21:19:49Z"
  mac: ENC[AES256_GCM,data:YtVaz0IPexCjw9j/owMn98+gldpIBhcV9ZYrYuaWXjv5WySyTRN3cYr0ALGBnFdkAl2DZdzRILwz1C8Iu7qddlVHWzdOnDU1OLRYiKId6DIJyfmgSD4wjHDZrVdXgvDuNXgoyk57emMwAdzNOU7A5T1vBE/WWMutPkMgYG3jnEI=,iv:VSkImwdcIjqkafDm0Rh/Cp2wMJ0D3e9cgBAJzAznIxE=,tag:s92YDn645nlOPiuYL+aQaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
