---
# Patch to add resource limits to Trident containers
# Prevents unbounded memory growth and ensures proper resource allocation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-controller
  namespace: trident
spec:
  template:
    spec:
      containers:
        - name: trident-main
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
        - name: csi-provisioner
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
        - name: csi-attacher
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
        - name: csi-resizer
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
        - name: csi-snapshotter
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
        - name: storage-api-server
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
