apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: ai
type: Opaque
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:lqq9azYbMEc8lwtr46PDadx0gToKernEn7Vend4XBDeFVVy9KSqWhXfyhRU=,iv:3oKuPE0d/4/m9QHJNuZKRZNdmauUkMI2Lhz4KWNAzSI=,tag:bsdEFQ/jPYiNwgq3jeF6yQ==,type:str]
  OPENID_PROVIDER_URL: ENC[AES256_GCM,data:ELpK7Tgt3jan/UVtVxRosDDaWMZzrFaJm8JljiXMtaDUM1uBPIEkT2/uABMlpDjOnQChkx+lspbe8ila9ENeVWz+Op+Pw9NPhnDL6nUaoDWrmGj8JjO3xMxG,iv:yhK2Cm4qd99ZJR0GdInRpA4p6LtfrLTdx7T1Ewyjl40=,tag:ti88cA2JeNWy+KkuFuj8bg==,type:str]
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:yEE7Y6kPo84ULmavh+YGtRWA0m9zvkltCHGz3p+m407eplfhPFTJIg==,iv:V1E/TY+b6ybHyx2oe3CHOlz54AGK7piYE/NMLlx8/Mw=,tag:EUzptBix0WHKyPz0Befmbg==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pJI6L2zlpvhGR2P5zXUvYVD34emszKpyNsckYSgKhfGB3PUkDxdWpsspxEP96qBr0G+ryThT7Wu/U1dxevdTVqLStdentds9kOUNTrbAcfcYUlmoQ7BK4TK+YXmaGcY6+ZuEgPkA0NmwlUUiify+0zli17ereXRHe8XCdXT4djo=,iv:8H+ivRU3nbCRouUtugzrlsN/CYKi9gwOkMDZIqeKyfw=,tag:BWUCTxzoRCSthsmwQK1dUQ==,type:str]
  OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:cZIkXMNCi2Vo,iv:Ib2y5Ebu6Lvg5zw8b4Sijjr6M+PzjjGnVWf0YfgL/rY=,tag:IZGvbFkWfTmXVSKvM4FnzA==,type:str]
  ENABLE_OAUTH_SIGNUP: ENC[AES256_GCM,data:E+dKWA==,iv:wyUJM/k3zAI7nyKhbf9MlDtRSYZeB8SicVKZB1GOxNI=,tag:2N8nP/wNkrDEhq0beC9zmg==,type:str]
  OAUTH_MERGE_ACCOUNTS_BY_EMAIL: ENC[AES256_GCM,data:F9X8fA==,iv:r0IEFsRMFB9Zt+ygX+YuTeObaiJ72tNt4q83hjytvlg=,tag:ow9TuGgmEEmF1KRwMn3RAQ==,type:str]
  WEBUI_URL: ENC[AES256_GCM,data:DGPtO9agWKE9Az5rUkvv65nPqFdtGzC6ME4b4C9smLWd1SMVrA==,iv:iIMKn0togWq4uTPSeFNwMXiLg+spsc4EvPfgkz9+Egk=,tag:suPI+cmi2LaY9vmshdXHPw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dGhaaktXci9WS2Vvd1Bt
        d3JuaHEwTmEwQWRkVy9USDlhaUxqaTJRRGpzCjNMcXRGbzcxMEx4L2E2ZVZlVWdX
        Wm5NVUR2aUtISkdOTGVqZmtlUFZZMDgKLS0tIFNabWNBTEwxbHNocWpCZzk0RXlq
        YzFiU3VwVXA1ckxZN29kakU1bXZ5aWcKDXb7rbARCjSPrFe+w6Vc+/mZNsyu3Wws
        TwTD4XVePWFW+NJnAKMTpsX/rYpv2h2thfsXC2xwAYhhLSgznBzgYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T21:19:47Z"
  mac: ENC[AES256_GCM,data:p1pXuXdkbVwmLFMWsETMp7SkXO+OUMlItw346q05W5P/cToOvH6caBCgfCnsoL6NqFL3YT0I5QMW35sd3mOUfwzrNbLb8MuJ2AnZr/fPDqr6pm4XOGBUhBVJrvWP+vXvrkrn+uho5unGE5eJJLoBFAd2MOjDFt0z+TcybpD8iEo=,iv:Nc0832aO+nRDWSdV8r8lt/yicbhZvao4GsoEpXEFelw=,tag:NmjmE+7yBJZDhshIEVg0Dw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
